LiveTL/HyperChat

postcss.config.js, webpack.config.js
Dev mode build (`yarn build`, `yarn start`) improvements:
1. HMR only enabled in watch mode (`yarn start`, `yarn build --watch`)
2. Always tree shake CSS (`purgecss`), even in dev mode, to avoid gigantic CSS files
3. Don't minimize in `manifest.json` and always concatenate output modules in dev mode for easier-to-understand output
=> Development mode build improvements

src/manifest.json, webpack.config.js
Using remote sources and `unsafe-eval` are not allowed by Mozilla's Add-on Policies, so this removes it from production builds and only adds it to development builds where webpack source maps requires eval.
=> Only add content_security_policy on dev builds

package.json, src/components/HyperchatButton.svelte, src/manifest.json, src/ts/storage.ts, tsconfig.json, yarn.lock
Start using extension storage instead of `localStorage` via [svelte-webext-stores](https://github.com/ChrRubin/svelte-webext-stores) by yours truly. The lib is fully TypeScript-ed and migrating to MV3 whenever that happens should be as simple as adding a parameter.
For now this is only used for the enable HC toggle, but it'll open up the opportunity to implement other settings related feature requests.
Fixes #31.
=> Use extension storage

src/components/Hyperchat.svelte, src/ts/chat-utils.ts, src/ts/queue.ts, src/ts/typings/chat.d.ts
Various tweaks that should help with HyperChat performance, especially with slower hardware:
- Queued messages from the YTC JSON parser are sent in 250ms batches, instead of on each individual message. Reduces the frequency of svelte array updates.
This is a breaking change in the background messaging API that will require an update on LTL side (LiveTL/LiveTL@9893b3c).
- Chat history size is reduced from 250 to 150. Nobody needs to scroll that much anyway. 150 is based on Twitch chat.
- Message truncation is changed from running on a timer to being based on chat history size. Truncation is only done if the amount of messages is 20 larger than chat history size, which will then be spliced down to the chat history size. Helps spread DOM operations into smaller chunks during heavy chat …
=> Performance tweaks

src/components/TranslatedMessage.svelte
Adding fade to each text block was making the browser calculate opacity for each of them, which killed performance HARD.
=> Remove fade on each text block

src/components/TranslatedMessage.svelte
Paid message text colors from YT JSON were getting overridden by the text color classes here.
The correct text colors should already be set on the ancestors, so there's no need to set the "stock" text colors again anyway.
=> Fix paid message text color

src/ts/chat-parser.ts
I figured out a trick to make the delay negligible.
When a chunk is received and is completely sorted, we assume that the first message in the chunk is meant to be displayed immediately. All messages that follow are timed relative to the first message. I think this is what ytc does internally, since the timing is very very close to default ytc. So much so that screenshots in chilledcow chat show an identical list of messages
left hc, right ytc.
=> reduced chat delay

src/scripts/chat-injector.ts, src/scripts/chat-interceptor.ts, src/ts/chat-utils.ts
The duplicate injection check is now only done by standalone HC, so only standalone HC will stop injecting its scripts when an existing injection is detected, and not LTL. A 500ms delay is added for standalone HC to help with the race condition around extension loading.
I've also removed the `readyState === 'loading'` stuff since I never got it to work properly.
Fixes LiveTL/LiveTL#394.
=> Fix LTL compatibility issue (again)

src/components/Hyperchat.svelte, src/scripts/chat-background.ts, src/scripts/chat-injector.ts, src/scripts/chat-interceptor.ts, src/ts/typings/chat.d.ts
So apparently `setTimeout` with 0 delay doesn't always execute immediately, which was causing LTL to fail randomly because the YTC interceptor haven't loaded.
The `chat-interceptor` and `chat-injector` scripts will now run without `setTimeout` on LTL, which was the previous behaviour. While this was enough to fix the issue, I've added response messages so LTL can handle failed registration, just in case.
=> Load scripts immediately for LTL

src/components/Hyperchat.svelte, src/components/MembershipItem.svelte, src/components/Message.svelte, src/components/MessageRuns.svelte, src/components/PaidMessage.svelte, src/components/PinnedMessage.svelte, src/components/Settings.svelte, src/components/StickyBar.svelte, src/components/SuperchatViewDialog.svelte, src/components/TimedItem.svelte, src/components/WelcomeMessage.svelte, src/components/changelog/Changelog.svelte, src/components/settings/InterfaceSettings.svelte, src/manifest.json, src/scripts/chat-background.ts, src/scripts/chat-interceptor.ts, src/stylesheets/scrollbar.css, src/ts/chat-parser.ts, src/ts/chat-utils.ts, src/ts/queue.ts, src/ts/storage.ts, src/ts/typings/chat.d.ts, src/ts/typings/ytc.d.ts
Implements https://github.com/LiveTL/HyperChat/issues/49
=> Add support for persistent superchats

src/components/Hyperchat.svelte, src/components/MessageRuns.svelte
this pr is fairly urgent, @r2dev2 @ChrRubin please review and approve as soon as possible
this happens when a duplicate message entry is added to the message array. svelte doesn't know what to do with duplicate keys, freezing the entire app.
the solution i implemented is to use a set of messageIds, tracking all rendered keys and checking against the set before adding to the message array. performance should be fine because js Set is sublinear time (`O(1) <= x < O(n)`), and even if close to `O(n)`, our `n` is like 250
=> add duplicateKeyBlocker to fix freezing issues

src/components/Hyperchat.svelte, src/components/HyperchatButton.svelte, src/ts/storage.ts
taishi didn't know that hyperchat had user reporting and blocking because he had hyperchat turned off and never saw the changelogs (outside of the minimized livetl changelogs). i think there are probably quite a few people who have hyperchat disabled most of the time because of something they dont like, not realizing that the feature has been implemented recently. this chip would help alert those users that there's new stuff they don't know about
when hovered, the chip chevron turns into an `x`.
=> show chip if hc updates while it's disabled

src/scripts/chat-background.ts
Currently, playerProgress event is only forwarded to YouTube clients (HyperChat and Youtube LiveTL). It needs to be forwarded to twitch clients (Twitch LiveTL) for https://github.com/LiveTL/LiveTL/issues/428.
=> Forward player timestamp to twitch clients

README.md, package.json, src/components/Hyperchat.svelte, src/manifest.json, src/scripts/chat-background.ts, utils/package.js, vite.config.ts
Adds support for MV3 in Firefox. Some things to note:
1. ff does not support service workers in their mv3 "support"
2. ff does not support extension to content script channels in their mv3 "support"
1. use bg script for ff and service workers for chrome
* implies that chrome and ff need completely different manifests (one is not superset of other)
* introduce `yarn dev:firefox` and `yarn dev:chrome` and make `yarn start` alias for `yarn dev:chrome`
2. proxy extension to content script messages through background script for ff
* unsure how long bg script for ff persists, I _think_ it should stay up as long as chat is active?
* should give to ff beta testers to make sure it actually works over long intervals
=> Firefox MV3

.eslintrc.js, package.json, src/components/Hyperchat.svelte, src/manifest.json, src/scripts/chat-background.ts, src/ts/storage.ts, yarn.lock
Add custom mechanism to track bytes usage of chrome storage because firefox hasn't implemented getBytesUsed on `chrome.storage.local`
We can add a hook for exceeding storage quota (that could be user-controlled) later either by:
* send a message from bg script when it sees bytesused > quota
* subscribe to bytesused store and see if it exceeds a limit `$: if ($bytesUsed > quota) { ...`
so such a hook is not needed in this pr.
=> Track Bytes Usage of Storage

src/components/Hyperchat.svelte, src/ts/messaging.ts
Ping service worker from hyperchat.svelte every 15s to keep it alive as service workers are killed every 30s.
=> Ping service worker

src/components/Hyperchat.svelte, src/ts/chat-utils.ts, src/ts/typings/chat.d.ts
So #125 seems to not be enough for preventing chat port disconnects so we try adding reconnection logic to the ports.
I tested on [Amelia Watson's stream](https://www.youtube.com/watch?v=xcdlTH2FZEo) in Firefox and the service worker remained alive.
=> Reconnecting Chat Port

src/components/HyperchatButton.svelte
Fixes #139 
Unsure if this style override is even necessary anymore but the rules dialog uses z-index 3 so this will paper over the issue for now, and I don't believe it reintroduces #134/etc.
Tested with Hyperchat enabled and disabled, handles both cases for the linked issue.
Alternatives:
Overriding the rules dialog's z-index to be 101 or something instead of doing this just seems like it will create a cascading set of overrides for stock YT chat behavior, which doesn't seem like the play.
=> Update z-index to prevent chat from showing up over 'rules' dialog

src/components/ChatSummary.svelte, src/components/Hyperchat.svelte, src/components/settings/InterfaceSettings.svelte, src/ts/chat-parser.ts, src/ts/storage.ts, src/ts/typings/ytc.d.ts
* Uses subheader as a link to [Google's support site for AI summaries](https://support.google.com/youtube/thread/18138167?hl=en&msgid=284199217)
* Dismissable and collapsible like pinned messages, but unlike stock YT it does not auto-dismiss after 12 seconds
* Setting to hide it entirely (will update its visibility based on setting immediately without refresh)
* Tested on ffox and on mv3 branch with chrome.
It's not perfect (icon and showtime fields remain unused right now) but it's pretty functional. Collapsing and dismissing both work as intended.
There are some hacky bits involved already to split the runs into header vs subheader vs message, so better ways to handle that would be nice, but YT's format for this action isn't ideal.
I tried adding the iconType stuff, but it resulted in …
=> Show YT's AI chat summary in a 'pinned'-style box if it is present

src/scripts/chat-injector.ts, src/ts/chat-constants.ts
The Android app doesn't embed the extension anymore, so this is just making the code unnecessarily complex.
=> Remove Android logic

src/components/ChatSummary.svelte, src/ts/chat-parser.ts
YouTube by default will dismiss the Chat Summary banner after bannerTimeoutMs (usually 12 seconds). Hyperchat currently does not dismiss the banner at all.
This change picks up YT's behavior, but instead of dismissing the banner, just collapses it.
The timer for collapsing the banner is cancelled if the banner gets manually collapsed.
This also changes summary.showtime from seconds to milliseconds.
Tested in mv3 on chrome, assuming ffox will work fine on master.
=> Auto-collapse Chat Summary banner after bannerTimeoutMs

src/components/HyperchatButton.svelte
This override breaks any dialogue that shows up over chat (ending Q&As, etc), and doesn't actually appear to be used for any Hyperchat feature.
=> Remove z-index override for yt-live-chat-renderer entirely

src/components/ChatSummary.svelte, src/components/PinnedMessage.svelte, src/ts/chat-parser.ts, src/ts/chat-utils.ts, src/ts/typings/ytc.d.ts
This also updates the impl in ChatSummary, and adds a fix for responseIsAction for summary (in case YT ever starts sending summary in liveChatContinuation instead of initial data).
Note that in all cases, the behavior is auto-collapse instead of YT's default behavior of removing certain banners entirely after the time expires.
bannerProperties exists both on the top-level object as well as inside the liveChatBannerRenderer.
This impl does the following:
- Get top-level isEphemeral.
- If true, use top-level bannerTimeoutMs, or 0 if not present, and return.
- If false, use top-level autoCollapseDelay, or liveChatBannerRenderer autoCollapseDelay if not present, or 0 if also not present, and return.
In stock YT, Redirects and AI Chat Summary use the top-level properties with isEphemeral=true …
=> Add auto-collapse capability to pinned messages based on timeout provided by bannerProperties

src/components/Hyperchat.svelte, src/components/MessageRuns.svelte, src/components/RedirectBanner.svelte, src/ts/chat-parser.ts, src/ts/chat-utils.ts, src/ts/typings/ytc.d.ts
Supports send and receive, uses the urlEndpoint or watchEndpoint link to open a new tab with the given url if the button is clicked
This also adds support for bold text (but not deemphasized text yet) to MessageRun
This does not implement contextMenuButton at all yet, only inlineActionButton.
Has the same auto-collapse behavior as other banner messages.
Built on top of #156 
Very hacky URL handling and button handling at the moment.
"Redirect Notice" is added to the header because it looks a bit silly without anything there.
"Redirect profile photo" is set as the alt text for the image since the author's actual name is only available elsewhere and it would be too hacky to try to grab it.
Tested on mv3 w/ chrome
=> Implement rudimentary redirect banner

package.json, src/components/Hyperchat.svelte, src/components/HyperchatButton.svelte, src/components/WelcomeMessage.svelte, src/manifest.json, src/ts/chat-constants.ts, src/ts/typings/vite-env.d.ts, vite.config.ts
- Move hardcoded version to package.json instead of src/manifest.json
- Handle browser branching logic based on build constant instead
=> More build cleanup

src/components/Hyperchat.svelte, src/components/PollResults.svelte, src/ts/chat-parser.ts, src/ts/chat-utils.ts, src/ts/typings/ytc.d.ts
Closes #110
Uses gray as the ProgressLinear color so that the white bar background shows up (tried all other options, it either made it completely invisible or had no background).
The actionId changes are so that multiple things can be removed via the removal message (e.g. polls) instead of only pinned messages.
Actual voting panel isn't implemented because it SEEMS like it *just works* with Hyperchat enabled already; no need to try to replace it.
=> Add implementation for showing poll results, make unpin action actionId-aware
